local M = {}

local names = {
  "3024 Night",
  "Abernathy",
  "Adventure",
  "AdventureTime",
  "Afterglow",
  "AlienBlood",
  "Andromeda",
  "Argonaut",
  "Arthur",
  "AtelierSulphurpool",
  "Atom",
  "Aurora",
  "Ayu Mirage",
  "Banana Blueberry",
  "Batman",
  "Belafonte Night",
  "BirdsOfParadise",
  "Blazer",
  "Blue Matrix",
  "BlueBerryPie",
  "BlueDolphin",
  "BlulocoDark",
  "Borland",
  "Breeze",
  "Broadcast",
  "Brogrammer",
  "Builtin Dark",
  "Builtin Pastel Dark",
  "Builtin Solarized Dark",
  "Builtin Tango Dark",
  "C64",
  "CGA",
  "Calamity",
  "Chalk",
  "Chalkboard",
  "ChallengerDeep",
  "Chester",
  "Ciapre",
  "Cobalt Neon",
  "Cobalt2",
  "CrayonPonyFish",
  "Cyberdyne",
  "Dark Pastel",
  "Dark+",
  "Darkside",
  "Desert",
  "DimmedMonokai",
  "Django",
  "DjangoRebornAgain",
  "DjangoSmooth",
  "Doom Peacock",
  "DoomOne",
  "DotGov",
  "Dracula+",
  "Dracula",
  "Duotone Dark",
  "ENCOM",
  "Earthsong",
  "Elemental",
  "Elementary",
  "Espresso Libre",
  "Espresso",
  "Fahrenheit",
  "Fairyfloss",
  "Fideloper",
  "FirefoxDev",
  "Firewatch",
  "FishTank",
  "Flat",
  "Flatland",
  "Floraverse",
  "ForestBlue",
  "Framer",
  "FunForrest",
  "Galaxy",
  "Galizur",
  "GitHub Dark",
  "Glacier",
  "Grape",
  "Grass",
  "Grey-green",
  "Gruvbox Dark",
  "Guezwhoz",
  "HaX0R_BLUE",
  "HaX0R_GR33N",
  "HaX0R_R3D",
  "Hacktober",
  "Hardcore",
  "Harper",
  "Highway",
  "Hipster Green",
  "Hivacruz",
  "Homebrew",
  "Hopscotch.256",
  "Hopscotch",
  "Hurtado",
  "Hybrid",
  "IC_Green_PPL",
  "IC_Orange_PPL",
  "IR_Black",
  "Jackie Brown",
  "Japanesque",
  "Jellybeans",
  "JetBrains Darcula",
  "Kibble",
  "Kolorit",
  "Konsolas",
  "Lab Fox",
  "Laser",
  "Later This Evening",
  "Lavandula",
  "LiquidCarbon",
  "LiquidCarbonTransparent",
  "LiquidCarbonTransparentInverse",
  "Man Page",
  "Mariana",
  "MaterialDark",
  "MaterialDarker",
  "MaterialDesignColors",
  "MaterialOcean",
  "Mathias",
  "Medallion",
  "Mirage",
  "Misterioso",
  "Molokai",
  "MonaLisa",
  "Monokai Remastered",
  "Monokai Soda",
  "Monokai Vivid",
  "N0tch2k",
  "Neon",
  "Neopolitan",
  "Neutron",
  "NightLion v1",
  "NightLion v2",
  "Nocturnal Winter",
  "Obsidian",
  "Ocean",
  "Oceanic-Next",
  "OceanicMaterial",
  "Ollie",
  "OneHalfDark",
  "Operator Mono Dark",
  "Overnight Slumber",
  "PaleNightHC",
  "Pandora",
  "Paraiso Dark",
  "PaulMillr",
  "PencilDark",
  "Peppermint",
  "Pnevma",
  "Popping and Locking",
  "Pro",
  "Purple Rain",
  "Rapture",
  "Raycast_Dark",
  "Red Alert",
  "Red Planet",
  "Red Sands",
  "Relaxed",
  "Retro",
  "Rippedcasts",
  "Rouge 2",
  "Royal",
  "Ryuuko",
  "Sakura",
  "Scarlet Protocol",
  "SeaShells",
  "Seafoam Pastel",
  "Seti",
  "Shaman",
  "Slate",
  "SleepyHollow",
  "Smyck",
  "Snazzy",
  "SoftServer",
  "Solarized Darcula",
  "Solarized Dark - Patched",
  "Solarized Dark Higher Contrast",
  "SpaceGray Eighties Dull",
  "SpaceGray Eighties",
  "SpaceGray",
  "Spacedust",
  "Spiderman",
  "Square",
  "Sublette",
  "Subliminal",
  "Sundried",
  "Symfonic",
  "Synth Midnight Terminal Dark (base16)",
  "synthwave",
  "Synthwave (Gogh)",
  "synthwave-everything",
  "SynthwaveAlpha",
  "SynthwaveAlpha (Gogh)",
  "Teerb",
  "Thayer Bright",
  "The Hulk",
  "Tinacious Design (Dark)",
  "Tomorrow Night Blue",
  "Tomorrow Night Bright",
  "Tomorrow Night Burns",
  "Tomorrow Night Eighties",
  "Tomorrow Night",
  "ToyChest",
  "Treehouse",
  "Twilight",
  "Ubuntu",
  "UltraDark",
  "UltraViolent",
  "UnderTheSea",
  "Urple",
  "Vaughn",
  "VibrantInk",
  "Violet Dark",
  "WarmNeon",
  "Wez",
  "Whimsy",
  "WildCherry",
  "Wombat",
  "Wryan",
  "Zenburn",
  "arcoiris",
  "ayu",
  "coffee_theme",
  "cyberpunk",
  "darkermatrix",
  "darkmatrix",
  "deep",
  "duckbones",
  "iceberg-dark",
  "idea",
  "idleToes",
  "jubi",
  "kanagawabones",
  "lovelace",
  "matrix",
  "midnight-in-mojave",
  "neobones_dark",
  "purplepeter",
  "rebecca",
  "seoulbones_dark",
  "shades-of-purple",
  "synthwave-everything",
  "synthwave",
  "tokyonight-storm",
  "vimbones",
  "wilmersdorf",
  "zenbones_dark",
  "zenwritten_dark",
}

function M.get()
  local i = math.random(#names)
  return names[i]
end

return M
