[CmdletBinding()]
param()

$sharedRoot = Join-Path $PSScriptRoot ".."
$basePath = Join-Path $PSScriptRoot "base.ghostty"
$dstPath = Join-Path $env:LOCALAPPDATA "ghostty/config.ghostty"

$fontPath = Join-Path $sharedRoot "font.json"
$schemePath = Join-Path $sharedRoot "scheme.json"
$snippetPath = Join-Path $sharedRoot "snippet.json"

function Read-Json {
  param(
    [Parameter(Mandatory=$true)][string]$Path,
    [Parameter(Mandatory=$true)][string]$Label
  )

  if (-not (Test-Path $Path)) {
    Write-Host "No $Label found at '$Path'. Skipping."
    return $null
  }

  try {
    return Get-Content -Path $Path -Raw -ErrorAction Stop | ConvertFrom-Json
  } catch {
    Write-Warning "Failed to parse $Label at '$Path'. Skipping. $_"
    return $null
  }
}

function Read-Lines {
  param(
    [Parameter(Mandatory=$true)][string]$Path,
    [Parameter(Mandatory=$true)][string]$Label
  )

  if (-not (Test-Path $Path)) {
    Write-Error "Missing $Label at '$Path'."
    exit 1
  }

  try {
    return Get-Content -Path $Path -ErrorAction Stop
  } catch {
    Write-Error "Failed to read $Label at '$Path'. $_"
    exit 1
  }
}

function Ensure-ParentDirectory {
  param(
    [Parameter(Mandatory=$true)][string]$Path
  )

  $directory = Split-Path -Parent $Path

  if ($directory -and -not (Test-Path $directory)) {
    try {
      $null = New-Item -Path $directory -ItemType Directory -Force -ErrorAction Stop
    } catch {
      Write-Error "Failed to create destination directory '$directory'. $_"
      exit 1
    }
  }
}

function ConvertTo-GhosttyString {
  param(
    [AllowNull()][string]$Value
  )

  if ($null -eq $Value) {
    return '""'
  }

  $builder = New-Object System.Text.StringBuilder
  [void]$builder.Append('"')

  foreach ($char in $Value.ToCharArray()) {
    $code = [int][char]$char

    if ($char -eq '"') {
      [void]$builder.Append('\"')
      continue
    }

    if ($char -eq '\') {
      [void]$builder.Append('\\')
      continue
    }

    if ($char -eq "`r") {
      [void]$builder.Append('\r')
      continue
    }

    if ($char -eq "`n") {
      [void]$builder.Append('\n')
      continue
    }

    if ($char -eq "`t") {
      [void]$builder.Append('\t')
      continue
    }

    if ($code -lt 0x20 -or $code -gt 0x7E) {
      [void]$builder.AppendFormat('\\x{0:x2}', $code -band 0xFF)
    } else {
      [void]$builder.Append($char)
    }
  }

  [void]$builder.Append('"')
  return $builder.ToString()
}

function Add-PaletteLines {
  param(
    [Parameter(Mandatory=$true)][System.Collections.IList]$Lines,
    [Parameter(Mandatory=$true)][psobject]$Scheme
  )

  $paletteMap = @(
    @{ Index = 0;  Value = $Scheme.black },
    @{ Index = 1;  Value = $Scheme.red },
    @{ Index = 2;  Value = $Scheme.green },
    @{ Index = 3;  Value = $Scheme.yellow },
    @{ Index = 4;  Value = $Scheme.blue },
    @{ Index = 5;  Value = $Scheme.purple },
    @{ Index = 6;  Value = $Scheme.cyan },
    @{ Index = 7;  Value = $Scheme.white },
    @{ Index = 8;  Value = $Scheme.brightBlack },
    @{ Index = 9;  Value = $Scheme.brightRed },
    @{ Index = 10; Value = $Scheme.brightGreen },
    @{ Index = 11; Value = $Scheme.brightYellow },
    @{ Index = 12; Value = $Scheme.brightBlue },
    @{ Index = 13; Value = $Scheme.brightPurple },
    @{ Index = 14; Value = $Scheme.brightCyan },
    @{ Index = 15; Value = $Scheme.brightWhite }
  )

  foreach ($entry in $paletteMap) {
    if ($entry.Value) {
      $Lines.Add("palette = $($entry.Index)=$($entry.Value)")
    }
  }
}

$baseLines = Read-Lines -Path $basePath -Label "base.ghostty"
$fontRoot = Read-Json -Path $fontPath -Label "font.json"
$schemeRoot = Read-Json -Path $schemePath -Label "scheme.json"
$snippetRoot = Read-Json -Path $snippetPath -Label "snippet.json"

$lines = [System.Collections.Generic.List[string]]::new()
$lines.AddRange([string[]]$baseLines)
$lines.Add("")
$lines.Add("# Generated by ghostty.ps1")

if ($fontRoot -and $fontRoot.font -and $fontRoot.font.Count -gt 0) {
  $font = Get-Random -InputObject $fontRoot.font
  $lines.Add("")
  $lines.Add("# Font: $($font.face)")
  $lines.Add("font-family = $(ConvertTo-GhosttyString $font.face)")
  $lines.Add("font-size = $($font.size)")
}

if ($schemeRoot -and $schemeRoot.scheme -and $schemeRoot.scheme.Count -gt 0) {
  $scheme = Get-Random -InputObject $schemeRoot.scheme
  $lines.Add("")
  $lines.Add("# Scheme: $($scheme.name)")
  $lines.Add("foreground = $($scheme.foreground)")
  $lines.Add("background = $($scheme.background)")
  $lines.Add("cursor-color = $($scheme.cursorColor)")
  $lines.Add("cursor-text = $($scheme.background)")
  $lines.Add("selection-background = $($scheme.selectionBackground)")
  $lines.Add("selection-foreground = $($scheme.background)")
  Add-PaletteLines -Lines $lines -Scheme $scheme
}

if ($snippetRoot -and $snippetRoot.snippet -and $snippetRoot.snippet.Count -gt 0) {
  $lines.Add("")
  $lines.Add("# Command palette snippets")

  foreach ($snippet in $snippetRoot.snippet) {
    $title = ConvertTo-GhosttyString $snippet.name
    $input = ConvertTo-GhosttyString ("text:" + $snippet.command.input)
    $lines.Add("command-palette-entry = title:$title,action:$input")
  }
}

try {
  Ensure-ParentDirectory -Path $dstPath
  [System.IO.File]::WriteAllLines($dstPath, $lines)
} catch {
  Write-Error "Failed to write Ghostty config to '$dstPath'. $_"
  exit 1
}

Write-Host "Wrote Ghostty config to '$dstPath'."
