#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
shared_root="$(cd "$script_dir/.." && pwd)"

base_path="$script_dir/base.ghostty"
font_path="$shared_root/font.json"
scheme_path="$shared_root/scheme.json"
snippet_path="$shared_root/snippet.json"

if ! command -v jq >/dev/null 2>&1; then
    printf 'Error: jq is required to generate the Ghostty config.\n' >&2
    printf 'Install it with: brew install jq (macOS) or sudo apt install jq (Ubuntu).\n' >&2
    exit 1
fi

config_home=""
if [[ -n "${XDG_CONFIG_HOME:-}" ]]; then
    case "$XDG_CONFIG_HOME" in
        /*) config_home="$XDG_CONFIG_HOME" ;;
        *)
            printf 'Warning: XDG_CONFIG_HOME is not an absolute path; ignoring it.\n' >&2
            ;;
    esac
fi
if [[ -z "$config_home" ]]; then
    config_home="${HOME:-}/.config"
fi

dst_dir="$config_home/ghostty"
dst_path="$dst_dir/config.ghostty"

sep=$'\x1f'

read_optional() {
    local path="$1" label="$2" filter="$3" result

    if [[ ! -f "$path" ]]; then
        printf 'No %s found at %s. Skipping.\n' "$label" "$path" >&2
        return 0
    fi

    if ! result=$(jq -c "$filter" "$path" 2>/dev/null); then
        printf 'Warning: Failed to parse %s at %s. Skipping.\n' "$label" "$path" >&2
        return 0
    fi

    if [[ -z "$result" ]]; then
        printf 'No %s entries found in %s. Skipping.\n' "$label" "$path" >&2
        return 0
    fi

    printf '%s' "$result"
}

if [[ ! -f "$base_path" ]]; then
    printf 'Error: Missing base.ghostty at %s\n' "$base_path" >&2
    exit 1
fi

base_lines=()
while IFS= read -r line || [[ -n "$line" ]]; do
    line=${line%$'\r'}
    base_lines+=("$line")
done <"$base_path"

font_json=$(read_optional "$font_path" "font.json" '.font | select(type == "array" and length > 0)')
scheme_json=$(read_optional "$scheme_path" "scheme.json" '.scheme | select(type == "array" and length > 0)')
snippet_json=$(read_optional "$snippet_path" "snippet.json" '.snippet | select(type == "array" and length > 0)')

lines=("${base_lines[@]}")
lines+=("")
lines+=("# Generated by ghostty.bash")

if [[ -n "$font_json" ]]; then
    seed=$(( (RANDOM << 15) ^ RANDOM ))
    font_face=$(jq -r --argjson seed "$seed" '.[($seed % length)].face // empty' <<<"$font_json")
    font_size=$(jq -r --argjson seed "$seed" '.[($seed % length)].size // empty' <<<"$font_json")

    if [[ -n "$font_face" ]]; then
        font_family=$(jq -nr --arg face "$font_face" '
            def hex2:
                "0123456789abcdef" as $h
                | $h[(./16 | floor) % 16] + $h[.%16];
            def zig_escape:
                explode
                | map(if . == 34 then "\\\""
                      elif . == 92 then "\\\\"
                      elif . == 9 then "\\t"
                      elif . == 10 then "\\n"
                      elif . == 13 then "\\r"
                      elif . < 32 or . == 127 then "\\x" + hex2
                      else [.] | implode end)
                | join("");
            $face | zig_escape')
        lines+=("")
        lines+=("# Font: $font_face")
        lines+=("font-family = \"$font_family\"")
        if [[ -n "$font_size" ]]; then
            lines+=("font-size = $font_size")
        fi
    fi
fi

if [[ -n "$scheme_json" ]]; then
    seed=$(( (RANDOM << 15) ^ RANDOM ))
    scheme_obj=$(jq -c --argjson seed "$seed" '.[($seed % length)]' <<<"$scheme_json")

    IFS="$sep" read -r name fg bg cursor selbg \
        p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 \
        <<<"$(jq -r '
            [.name, .foreground, .background, .cursorColor, .selectionBackground,
             .black, .red, .green, .yellow, .blue, .purple, .cyan, .white,
             .brightBlack, .brightRed, .brightGreen, .brightYellow, .brightBlue,
             .brightPurple, .brightCyan, .brightWhite]
            | map(if . == null then "" else . end)
            | join("\u001f")' <<<"$scheme_obj")"

    if [[ -n "$name" ]]; then
        lines+=("")
        lines+=("# Scheme: $name")
    fi
    [[ -n "$fg" ]] && lines+=("foreground = $fg")
    [[ -n "$bg" ]] && lines+=("background = $bg")
    [[ -n "$cursor" ]] && lines+=("cursor-color = $cursor")
    [[ -n "$bg" ]] && lines+=("cursor-text = $bg")
    [[ -n "$selbg" ]] && lines+=("selection-background = $selbg")
    [[ -n "$bg" ]] && lines+=("selection-foreground = $bg")

    while IFS="$sep" read -r idx color; do
        [[ -n "$color" ]] && lines+=("palette = $idx=$color")
    done < <(jq -r --argjson seed "$seed" '
        .[($seed % length)] as $s |
        [[0, $s.black], [1, $s.red], [2, $s.green], [3, $s.yellow],
         [4, $s.blue], [5, $s.purple], [6, $s.cyan], [7, $s.white],
         [8, $s.brightBlack], [9, $s.brightRed], [10, $s.brightGreen],
         [11, $s.brightYellow], [12, $s.brightBlue], [13, $s.brightPurple],
         [14, $s.brightCyan], [15, $s.brightWhite]]
        | map(select(.[1] != null and .[1] != ""))
        | map((.[0] | tostring) + "\u001f" + .[1])
        | join("\n")' <<<"$scheme_json")
fi

if [[ -n "$snippet_json" ]]; then
    lines+=("")
    lines+=("# Command palette snippets")

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        lines+=("$entry")
    done < <(jq -r --arg sep "$sep" '
        def hex2:
            "0123456789abcdef" as $h
            | $h[(./16 | floor) % 16] + $h[.%16];
        def zig_escape:
            explode
            | map(if . == 34 then "\\\""
                  elif . == 92 then "\\\\"
                  elif . == 9 then "\\t"
                  elif . == 10 then "\\n"
                  elif . == 13 then "\\r"
                  elif . < 32 or . == 127 then "\\x" + hex2
                  else [.] | implode end)
            | join("");
        .[]
        | select(type == "object")
        | . as $s
        | (($s.name // "") | tostring) as $name
        | (($s.command // {}) | if type == "object" then ((.input // "") | tostring) else "" end) as $input
        | select(($name != "") and ($input != ""))
        | "command-palette-entry = title:\"" + ($name | zig_escape) + "\",action:\"text:" + ($input | zig_escape) + "\""' <<<"$snippet_json")
fi

if [[ ! -d "$dst_dir" ]]; then
    mkdir -p "$dst_dir" || {
        printf 'Error: Failed to create destination directory %s\n' "$dst_dir" >&2
        exit 1
    }
fi

tmp_path=""
if command -v mktemp >/dev/null 2>&1; then
    tmp_path=$(mktemp "$dst_path.XXXXXX" 2>/dev/null) || tmp_path=""
fi
if [[ -z "$tmp_path" ]]; then
    tmp_path="$dst_dir/.config.ghostty.$$"
fi

if ! printf '%s\n' "${lines[@]}" >"$tmp_path"; then
    rm -f "$tmp_path"
    printf 'Error: Failed to write temporary config at %s\n' "$tmp_path" >&2
    exit 1
fi

chmod 644 "$tmp_path" 2>/dev/null || true

if ! mv -f "$tmp_path" "$dst_path"; then
    rm -f "$tmp_path"
    printf 'Error: Failed to install config at %s\n' "$dst_path" >&2
    exit 1
fi

if [[ -f "$dst_dir/config" ]]; then
    printf 'Warning: legacy config detected at %s.\n' "$dst_dir/config" >&2
    printf 'Ghostty loads it after config.ghostty and it may override this generated config.\n' >&2
fi

if [[ "$(uname -s 2>/dev/null || true)" == "Darwin" ]]; then
    app_support_dir="$HOME/Library/Application Support/com.mitchellh.ghostty"
    if [[ -f "$app_support_dir/config.ghostty" || -f "$app_support_dir/config" ]]; then
        printf 'Warning: macOS config detected at %s.\n' "$app_support_dir" >&2
        printf 'Ghostty loads it after the XDG config and it may override this generated config.\n' >&2
    fi
fi

printf 'Wrote Ghostty config to %s\n' "$dst_path"
